version: '2'

services:

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "5602:443"
      - "5603:444"
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - es

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601" 
    env_file:
      - ./.env
    depends_on:
      - ${ELASTIC_HOST}
    environment:
      SERVER_NAME: ${KIBANA_HOST}
      ELASTICSEARCH_URL: ${ELASTIC_FULL_URL}
    restart: on-failure    
    networks:
      - es

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    env_file:
      - ./.env
    environment:
      SERVER_NAME: ${ELASTIC_HOST}
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    networks:
      - es

volumes:
  development-nginx-volume:
  development-elasticsearch-volume:
  development-kibana-volume:

networks:
  es:
